################################################
# Workflow name.
################################################
name: blazor_docker_azure                                        


################################################
# Define environment variables.
################################################
env:
  AZURE_WEBAPP_NAME:         dockerazuretest            
  AZURE_WEBAPP_PACKAGE_PATH: BlazorApp1\published   
  WORKING_DIRECTORY:         BlazorApp1  
  CONFIGURATION:             Release
  
  # could put these in env settings either.
  ACTIONS_STEP_DEBUG:   true
  ACTIONS_RUNNER_DEBUG: true


################################################
# ?emoji When is the workflow triggered.
################################################
on:       
 workflow_dispatch:
 push:                                             
   branches: [ master ]
 

jobs:
  ################################################
  # build job.
  ################################################
  build:     
    ################################################
    # 💻 Specify runner OS.
    ################################################      
    runs-on: ubuntu-latest   
    
    ################################################
    # Steps in the build job.
    ################################################     
    steps:
    ################################################
    # ️➡️ Checkout code.
    ################################################
    - name: Checkout code.                            
      uses: actions/checkout@v5
      
    ################################################
    # 🔧 Set up .NET.
    ################################################
    - name: Set up .NET                                 
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
        
    ################################################
    # 🧱 Build for Release.
    ################################################
    - name: Build for Release                          
      run: >
        dotnet build 
        --configuration Release
           

    ########################################################
    # 📘 Publish the app, i.e., create a deployment package.
    ########################################################
    - name: Publish
      run: > 
        dotnet publish  ${{ env.WORKING_DIRECTORY }}
        --configuration ${{ env.CONFIGURATION }} 
        --output        ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        --no-build 
        
    
    ################################################################
    # ☁️ Deploy to Azure Web apps using publish profile credentials.
    ################################################################
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with: 
        app-name:            ${{ env.AZURE_WEBAPP_NAME }}   
        package:             ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}        
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}    
